# Generated by Django 4.2.16 on 2024-10-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
