# Generated by Django 4.2.16 on 2024-10-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_first_name_en_usermodel_first_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name_uz',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name_uz',
        ),
    ]
