# Generated by Django 4.2.16 on 2024-10-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='SizeModel',
        ),
    ]
