# Generated by Django 4.2.16 on 2024-10-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_colormodel_remove_productmodel_colours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
    ]
