# Generated by Django 4.2.16 on 2024-10-20 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_colormodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(related_name='category_products', to='products.categorymodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(related_name='colored_products', to='products.colormodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_products', to='products.tagmodel'),
        ),
    ]
